#!/usr/bin/env bash
# Install and configure ufw firewall

sudo apt install ufw
sed -i 's/IPV6=.*/IPV6=yes/' /etc/default/ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow ssh
sudo ufw allow https
sudo ufw allow http
sudo ufw disable
sudo ufw enable
