#!/usr/bin/env bash
# This script displays all active IPv4 addresses on the machine
# ip -4 -o addr show | awk '{print $4}' | cut -d "/" -f 1 (a diff of doint it)

ifconfig | grep -Eo "inet (addr:)?([0-9]*\.){3}[0-9]*" | awk '{print $2}'
